### ISSUE TITLE
WIP?

### ISSUE THREAD

**Issue by lukasabino** [byteblenduk/whmcs-n8n#2]
This still in Work In Progress?

How can I install, test and help to develop this module?

**Comment by byteblenduk** [comment]
Hey,

I continued the work on it on a private gitea and have a working version running, i'll move the files over in the next day or 2 and get a release together,

I'll drop an update in here when it's ready.

**Comment by lukasabino** [comment]
Hello friend, I will wait for this release to test it on my base so I can contribute in some way.
